version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"  # Пробрасываем порт 80 контейнера на порт 8080 хоста

  frontend:
    build:
      context: .
      dockerfile: docker/front.dockerfile
    depends_on:
      - backend
    restart: unless-stopped
    ports:
      - "8081:80"  # Пробрасываем порт 80 контейнера на порт 8081 хоста