FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

# Копируем файлы проекта и восстанавливаем зависимости
COPY ./follow-me/follow-me/*.csproj ./
RUN dotnet restore

# Копируем все файлы и собираем приложение
COPY ./follow-me/follow-me/ ./
RUN dotnet publish -c Release -o out ./follow-me.csproj

# Собираем финальный образ
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app

# Копируем файлы конфигурации
COPY --from=build /app/out .
COPY ./follow-me/follow-me/appsettings*.json ./

ENTRYPOINT ["dotnet", "follow-me.dll"]